### ISSUE TITLE
qt.qpa.xcb: could not connect to display

### ISSUE THREAD

**Issue by oaix** [Tiryoh/docker-ros-desktop-vnc#28]
This image `tiryoh/ros-desktop-vnc   noetic    723aa1948265` can't show UI such as rviz because of no Qt platform plugin could be initialized. Some discuss about [Could not load the Qt platform plugin "xcb" in "" even though it was found](https://github.com/therecipe/qt/issues/775) has been found. But no useful solution can solve this problem in docker image. When run `rviz` get this error: 
![image](https://user-images.githubusercontent.com/10334694/131069708-0117f389-a916-47b7-8df8-ed3cc6852073.png)
Could you please give some advise?

**Comment by Tiryoh** [comment]
Hi @oaix, thanks for your report.
I tried but I could not able to reproduce. Could you tell me more detailed information?
* Which OS did you use for the host computer?
* How did you launch the container?

**Comment by Tiryoh** [comment]
I tried on Ubuntu 20.04, with `docker run --rm -p 6080:80 --shm-size=512m tiryoh/ros-desktop-vnc:noetic`.

https://user-images.githubusercontent.com/3256629/131215903-593eadf4-9e79-4367-bc0b-3532d1fda6ef.mp4

**Comment by oaix** [comment]
@Tiryoh Thank you for your reply.  
When opening terminal in browser as you do, this problem doesn't appear.   
I used `docker exec -it my_container bash` to enter the container, then I met this problem.

**Comment by Tiryoh** [comment]
> When opening terminal in browser as you do, this problem doesn't appear.
> I used docker exec -it my_container bash to enter the container, then I met this problem.

I see what you mean, did you override ENTRYPOINT or something?
I don't think bash can be started as it is now, because startup.sh is being called by ENTRYPOINT.
Could you share your Dockerfile? I might be able to figure out something more.
